code/modules/mob/dead/observer/observer.dm
Fixes ghost bobbing.
Haha ghost does funny move!
:cl:
fix: Ghosts are now animated properly again.
/:cl:
=> Fixes ghost bobbing.

_maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/IceBoxStation/IceBoxStation.dmm, _maps/map_files/KiloStation/KiloStation.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/tramstation/tramstation.dmm
Re-adds RnD consoles to RnD. Simple as.
So science can do the bare minimum without needing head approval to do so.
:cl:
qol: Research and Development now has research consoles again, denying them an excuse for not doing their jobs.
/:cl:
=> Re-adds RnD consoles to RnD

code/modules/projectiles/projectile/bullets/lmg.dm, code/modules/research/designs/mecha_designs.dm, code/modules/vehicles/mecha/equipment/weapons/mecha_ammo.dm, code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Makes the mech LMG actually a mech LMG.
The DPS is still the same for balancing reasons.
The mech LMG went from a basic 3 shot weapon to an actual minigun. What's NOT to love?
https://user-images.githubusercontent.com/52262416/171063053-6cb25c27-6310-41cf-aa3f-864858b4bb40.mp4
:cl:
add: The mech LMG "AC-2" now actually works like a mech LMG. Have fun Brigad- Roboticist.
/:cl:
=> Makes the mech LMG scary

code/modules/vehicles/mecha/_mecha.dm
What it says on the tin. 5 damage now gets applied on each punch.
This was unintentionally removed during the mech refactor.
:cl:
fix: Non-combat mechs now do 5 brute damage again for their punches.
/:cl:
=> Makes normal mechs do damage again

_maps/RandomRuins/LavaRuins/lavaland_surface_sloth.dmm, code/modules/ruins/lavalandruin_code/sloth.dm
Fixes the sloth note.
It is utterly CRUCIAL that this gets fixed, seriously gamebreaking bug bro, trust me.
:cl:
fix: The paper note in the sloth ruin now works properly.
/:cl:
=> Fixes sloth note

code/datums/quirks/negative.dm
Makes Unstable a mood quirk.
It's already a mood quirk but no one bothered to classify it as such.
If we ever need to disable mood quirks for whatever reason, this will help.
:cl:
fix: Unstable is now counted as a mood quirk.
/:cl:
=> Makes unstable a mood quirk

code/modules/wiremod/components/action/speech.dm
Sanitizes the circuit speech component.
Less XK class exploits = more gooder.
Thanks TCEO.
:cl:
fix: Sanitized the circuit speech component.
/:cl:
=> Sanitizes circuit speech component

code/modules/mob/living/carbon/human/emote.dm
*scream
It's funny.
:cl:
add: You can now audibly scream with the *scream emote.
/:cl:
=> Makes you able to scream on command.

_maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/IceBoxStation/IceBoxStation.dmm, _maps/map_files/KiloStation/KiloStation.dmm, _maps/map_files/MetaStation/MetaStation.dmm, code/controllers/subsystem/id_access.dm, code/controllers/subsystem/job.dm, code/controllers/subsystem/ticker.dm, code/game/machinery/computer/communications.dm, code/game/objects/items/storage/secure.dm, code/game/objects/structures/crates_lockers/closets/secure/security.dm, code/modules/mob/dead/new_player/new_player.dm
Removes the spare safe from every map in rotation and from the code, Heads no longer get the code for anything either
The spare now spawns in the captain's locker.
Fighting for the spare very cool.
:cl:
del: Removed the spare safe and the concept of chain of command from the code
/:cl:
=> Spare safe removal

code/modules/research/techweb/all_nodes.dm, code/modules/surgery/organs/cybernetics/_augments.dm, code/modules/surgery/organs/cybernetics/augments_chest.dm, code/modules/surgery/organs/cybernetics/augments_internal.dm
Makes basic NT cyberlink tech cheaper, hopefully fixes the current issues with cybernetics
NT1.0 cyberlinks should be dirt cheap to get, and bugfixes are always good
:cl:
balance: NT1.0 cyberlink tech is cheaper
fix: Hopefully fixes all current issues with cyberlinks
/:cl:
=> Balance changes around cybernetics and fixes some buugs

code/modules/research/designs/autolathe_designs.dm
This pull request will add plates to the autolathe, essentially righting a great wrong.
You can print everything else except plates for some god forsaken reason, what the fuck are you meant to burn your hands eating hot spaghetti? this is a travesty that must be corrected
:cl:
expansion: Adds plates to the autolathe
/:cl:
=> Adds plates to the autolathe

code/datums/components/religious_tool.dm, code/modules/holodeck/computer.dm
Fixes an exploit that lets people send unsanitized text to every player
:cl: 
fix: Removes a XSS vulnerability while picking religious sect.
/:cl:
=> Ports exploit fix from tg that was high priority 

code/datums/components/religious_tool.dm
sect_select and perform_rite are unsanitized, allowing a user to arbitrability spawn any path.
:cl:
fix: Fixes an exploit that allowed players to arbitrarily spawn any path.
/:cl:
=> Ports Fixes an exploit that allowed players to spawn arbitrary paths

code/game/machinery/computer/apc_control.dm
Fixes "toggle-minor" in apc_control.dm sending unsanitized text to admins.
it protecc it fix it port
:cl:
fix: Fixes an exploit that allowed players to send unsanitized text to admins.
/:cl:
=> Ports Fixes an exploit that allowed players to send unsanitized text to admins from tgstation

code/modules/ninja/suit/suit.dm
Fixes the ninja suit which I broke when removing suit cells, sorry.
Fixes #68 
:cl:
fix: Ninja suit properly handles cooldowns.
/:cl:
=> Fixes the ninja suit

code/modules/antagonists/cult/runes.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/human/human_helpers.dm
Its just stupid that most of people bleed out from wounds after being converted in a blood cult. Not only that but usually most cultists just convert people the sharp way of shanking them like in london (due to their own mistakes usually). 
~~Now if you convert a cultist, they get a boon of being basically just Ahealed.~~
Now it will just fix you up a bit, remove all wounds and replenish blood.
=> Being converted now aheals the cultie

code/__DEFINES/research.dm, code/game/machinery/doppler_array.dm, code/modules/research/rdconsole.dm, code/modules/research/techweb/_techweb_node.dm, code/modules/research/techweb/all_nodes.dm
This is the first step in tweaking ExperiSci.
This PR is going to add a radio to the console which is going to message respective department's radio channels connected with the node being researched. Furthermore, this PR is going to revert 50K general research point bomb and previous research point prices before Experisci. In addition, experiment discounts and requirements are gone.
:cl:
add: Revert 50k point scibomb
add: Nodes upon research announce research in respective department's radio channels related to the node
del: Remove experisci requirements and discounts
balance: Reduce point requirement for some nodes
:cl:
=> ExperiSci tweaks

code/modules/clothing/clothing.dm, code/modules/mob/living/carbon/human/human_update_icons.dm
port, credits to Shroopy
:cl:
fix: fixes female jumpsuit/skirt colors not updating correctly
/:cl:
=> fixes female jumpsuit/skirt colors not updating correctly

code/modules/reagents/reagent_containers/medigel.dm
BAD :(
GOOD :)
:cl:
fix: fixes medigel burst/spray message
/:cl:
=> fixes medigel burst/spray message

code/game/turfs/open/space/space.dm
Cleans up deadweight code from space turf initialization code, and moves code that will never run during mapload behind a mapload check.
This on my computer sped up initialization time by around 100 seconds, your mileage may vary.
=> Optimize space initialization during mapload.

tgui/packages/tgui/interfaces/Changelog.js
=> Rebrand Changelog

code/modules/vending/_vending.dm, code/modules/vending/wardrobes.dm, tgui/packages/tgui/interfaces/Vending.tsx
You will no longer have to pay for the drip.
idk
:cl:
add: clothing in clothing vendors is now free for jobs, except for premium clothing.
/:cl:
=> Makes job clothing vendors free for jobs from same department.

tgui/packages/tgui/interfaces/ChemReactionChamber.js
How did this even work locally?? and more importantly how the fuck did it even pass the checks?
=> fix the reaction chamber (actually)

code/controllers/subsystem/id_access.dm, code/game/objects/items/cards_ids.dm
Fixes AA-chip programmer not being able to remove access from a chip, and fixes setting template not updating card name.
I don't think this one needs a changelog, because these are all my fuckups anyways.
=> Some ID rework fixes.

tgui/packages/tgui/interfaces/AirlockElectronics.js, tgui/packages/tgui/interfaces/Vending.tsx
=> Fix vending machine and airlock electronics UI.

_maps/map_files/MetaStation/MetaStation.dmm
Fixes disposals in medical
removes stray segment in sci
Fixes disposals in medickal (psychology office) + removes stray disposals in maint near departures
:cl:
fix: Disposals in medical on meta now work
/:cl:
=> Fixes disposals in meta medial

code/modules/admin/verbs/maprotation.dm
Adds a bunch of options for custom map loading.
:cl:
admin: Admins can now set Z-Traits, space Z-level count, and minetype on custom map loading.
/:cl:
=> Add extra options to custom map loading

code/modules/reagents/chemistry/holder.dm
Lets reaction chambers accept chems again. Fixes ported from https://github.com/tgstation/tgstation/pull/57050 credits to time-green. Fixes #123 
Oh my god stop breaking please be the last time I don't want it to break anymore.
:cl:
fix: reaction chamber works again??
/:cl:
=> Fixing reaction chambers for real this time (right?)

_maps/map_files/Mining/Lavaland.dmm
Seems like I fucked up something in the smart pipe revert PR and lavaland base ended up missing a lot of scrubber pipes.
=> Fix lavaland piping.

code/game/objects/buckling.dm, code/modules/mob/mob.dm
Ports https://github.com/tgstation/tgstation/pull/60624 Credit to green water oranges.
It's not, I hate the secway, but I'm fixing it anyway.
:cl:
fix: you can use vehicles./:cl:
=> Ports Fixes vehicles From /tg/

code/controllers/configuration/entries/general.dm, code/controllers/subsystem/persistence.dm, config/config.txt
Requested by @rdragan
Allows you to adjust the numbers for the forced map rotation, or turn it off entirely.
Requested
:cl: Skog
config: Added configs for forced map rotation.
/:cl:
=> Adds config options to forced map rotation

_maps/map_files/MetaStation/MetaStation.dmm
adds in the missing pipe in atmos
fixes missing pipe in atmos, what to say
:cl: 
fix: fixes missing pipe in atmos oxygen mix line
/:cl:
=> Meta atmos fix

code/modules/plumbing/plumbers/synthesizer.dm, code/modules/reagents/chemistry/machinery/chem_assembler/chem_assembler.dm
It's on the tin
It's back in chem dispenser so it should be in all of other chem maker thingies too
:cl: 
balance: you can make chem silver in chem assembler and synthesizer 
/:cl:
=> add silver to chem assembler and synthesizer

code/modules/library/lib_machines.dm
Adds message to emagging book printer
Fixes #80
:cl:
fix: Library book printer now has emag message
/:cl:
=> Emag message on emagging book inventory management console

code/modules/jobs/card_accesses/station.dm
=> fixes bug where map job changes broke access for the modified job

code/__DEFINES/admin.dm, code/modules/admin/verbs/adminhelp.dm, code/modules/admin/verbs/adminsay.dm
Port of https://github.com/tgstation/tgstation/pull/61712  
We might want to choose or add a different sound, this uses bloop.ogg (the vote sound).
Ping and annoy your fellow admins idling in the lobby screen.
:cl: Thebleh
admin: Admins can now ping each other in asay
/:cl:
=> Adds asay pings

_maps/map_files/MetaStation/MetaStation.dmm
My 3 smooth braincells somehow thought that hotpiping o2 to pure is a smart fucking idea (its not) and I also noticed that we need better atmos quality control because we let that through 😂 
:cl:
fix: Fixes meta atmos for real
/:cl:
=> Actual meta atmos fix

code/modules/cargo/bounties/reagent.dm, code/modules/reagents/chemistry/reagents/other_reagents.dm, code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm, code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Just added Ammonium Nitrate an high explosive reagent that can be make using 1u EZ Nutrient, 1u Robust Harvest, 1u Left 4 Zed, 1u Welding Fuel the result is 4u of ammonium nitrate
More explosive chemical more fun!!
:cl:
add: Added Ammonium Nitrate as high explosive chemical and a fertilizer
/:cl:
=> Added Ammonium Nitrate (ANFO)

_maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
yeeee
Adds a Mauler wreckage to Syndicate Lavaland, alongside fixing an issue with the oxygen tank's piping. Also cornerwalls some shit and adds an autolathe. And a backup generator.
Cornerwalls are cool, autolathes can't make RCDs when hacked (tested) and the syndie lavaland O2 tank had a missing pipe that it now no longer lacks. Also a backup generator for if the turbine is fucked up regardless.
:cl:
add: Syndicate Lavaland now has:
add: an autolathe and Mauler wreckage
add: more cornerwalls
add: a new pipe to the oxygen tank so that the shit works
add: a backup generator with uranium. yes you can make a crude RTG with this
/:cl:
=> Syndicate Lavaland Polish

code/modules/clothing/gloves/color.dm
Literally nobody uses these. They had a chance of 1 in 7 to be the real thing, with an identical chance to be worse than nothing. 
Increased the odds of old insuls working to 2 in 3, since these are mainly on oldstation. Not giving them insuls that work is pretty cringe, now at least one pair should statistically work.
Maybe someone will pick these up once in a while.
:cl: Skog
balance: Budget insuls now work 50% of the time, up from <15% of the time.
/:cl:
=> Budget insuls work 50% of the time

code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
Adds changelings as a latejoin dynamic ruleset
There are litterally only three latejoin rulesets, and that sucks. Adds more variations to latejoin antags.
:cl: SuperSlayer
add: Added latejoin changelings
/:cl:
=> Adds latejoin changelings

code/modules/swarmers/swarmer.dm
As the title says
Balloon alerts are cool
:cl:
qol: Converted some swarmer messages to balloon alerts
/:cl:
=> Converts some swarmer messages to balloon alerts

code/modules/cargo/exports/xenobio.dm, code/modules/power/cell.dm, code/modules/power/smes.dm, code/modules/reagents/chemistry/recipes/slime_extracts.dm, code/modules/research/xenobiology/crossbreeding/_misc.dm, code/modules/research/xenobiology/crossbreeding/charged.dm, code/modules/spells/spell_types/charge.dm
hopefully reverts tgstation/tgstation/pull/54198.
Reverts a stupid nerf.
:cl:
add: Recharging yellow extract power cells
/:cl:
=> Re-adds yellow slime core recharge function

code/_onclick/hud/screen_objects.dm
UI code with observing is funny, so you have to make sure that the user clicking the UI button is not a ghost.
it just is.
:cl:
fix: Fixed ghosts being able to change people's intents.
/:cl:
=> Fix ghosts being able to change people's intents.

code/modules/antagonists/heretic/knowledge/void_lore.dm
closes: https://github.com/AetherStation/AetherStation13/issues/197
:cl:
fix: you can craft void blades again
/:cl:
=> fixes not being able to craft void blades

code/modules/research/designs/nanite_designs.dm, code/modules/research/nanites/nanite_programs/utility.dm, code/modules/research/techweb/all_nodes.dm
Distributed Computing and Neural Network are readded, which can provide a nice boost to research point gain to offset the points required for nanites a bit.
Because active point generation is not bad and people should be given opportunities to generate research points.
:cl:
add: Nanite research protocols are back, under the basic nanites technode.
/:cl:
=> Readds research point nanites

code/modules/research/designs/nanite_designs.dm, code/modules/research/nanites/nanite_programs/buffing.dm
This PR updates the nanite anti-stun program to work off stamina rather than hard stuns, updating it back into relevancy.
It now has 50% reduced impact of stamina damage on top of it's current effect.
More old stuff brought back into relevancy, what's not to love?
:cl:
balance: Updates the Nerve Support nanite program to also work with stamina.
/:cl:
=> Updates nanite anti-stuns.

code/game/turfs/change_turf.dm, code/modules/deathmatch/deathmatch_maps.dm
fixes #152, also I forgot to set the correct max players with the mech madness map and didn't feel like opening another PR for that.
nothing players need to care about.
=> Fix empty not emptying baseturfs, also a single value change in deathmatch.

code/modules/antagonists/heretic/eldritch_book.dm
Reverts AetherStation/AetherStation13#264
=> Revert "Fixes href exploit in codex cicatrix."

_maps/map_files/MetaStation/MetaStation.dmm, code/game/machinery/computer/Operating.dm, code/game/machinery/stasis.dm, code/modules/surgery/surgery.dm
does whats in the title of the pr and also removes the left over decals from the meta that i forgot to remove when i made the meta med revert pr. (im just lazy to atomize)
less tedium of moving patients one tile from the stasis bed to surgery table to start a goo
:cl:Pepsiman
qol: stasis beds and op computers work together again
/:cl:
=> makes possible to connect stasis beds to operating computers again

code/modules/antagonists/heretic/eldritch_book.dm
I just forgot `initial()`, also webedit PR moment.
=> fixes the codex cicatrix href exploit properly.

code/modules/surgery/advanced/bioware/nerve_splicing.dm
Updates Nerve Splicing; it also grants a 50% stamina reduction now.
This also stacks with the anti-stun nanite progam, making you around 75% more resistant against stuns total! (not 100% sure)
Updating old things back into relevancy.
:cl:
balance: Nerve Splicing surgery now takes stamina damage in mind. (50% reduction)
/:cl:
=> Updates Nerve Splicing Surgery.

code/__DEFINES/food.dm, code/datums/components/food/edible.dm, code/game/objects/items/food/bread.dm, code/game/objects/items/food/egg.dm, code/game/objects/items/food/frozen.dm, code/game/objects/items/food/lizard.dm, code/game/objects/items/food/meat.dm, code/game/objects/items/food/misc.dm, code/game/objects/items/food/pastries.dm, code/game/objects/items/food/sandwichtoast.dm, code/game/objects/items/food/snacks.dm
This PR brings back the old way of eating food.
Nobody likes to stand around, waiting for their little guy to eat something, seemingly incapable of moving legs while doing so.
:cl:
qol: Biting food is now instant again!
/:cl:
=> Makes biting food instant again.

code/_onclick/other_mobs.dm, code/modules/clothing/gloves/_gloves.dm, code/modules/ninja/suit/gloves.dm
fixes #277, this was caused by something I missed with interaction mode.
:cl:
fix: Fixed ninja gloves not being able to drain energy.
/:cl:
=> Fixes ninja glove draining.

code/modules/projectiles/projectile/energy/net_snare.dm
One character change that stops dragnet from runtiming
I like teleporting people into space with my teleport energy shotgun
:cl:
fix: dragnet no longer runtimes
/:cl:
=> Fix Dragnet

code/datums/mind.dm, code/modules/antagonists/cult/cult.dm, code/modules/antagonists/cult/runes.dm
Fixes cult spirit realm increasing cult size, also made spirit realm ghost lose the cult antag datum when removed.
:cl:
fix: Fixed cult spirit realm rune ghosts increasing cult size for eyes/halo.
/:cl:
=> Fix spirit realm ghosts increasing cult size.

code/datums/mutations/hulk.dm
What it says on the tin.
Enough is enough
:cl: Thebleh
balance: Balances Hulk.
/:cl:
=> Fixes Hulk

code/datums/mutations/hulk.dm
Reverts AetherStation/AetherStation13#289
=> Revert "Fixes Hulk"

code/modules/mob/living/carbon/human/species_types/felinid.dm
Makes cats like Dairy, raw and meat
Why the hell do cats not like eating rodents?
:cl:
add: Felinids now like eating mice
/:cl:
=> Felinids now like eating raw meat and mice, also, milk

code/game/objects/items/shields.dm
I should've expected something like that when making it an alt click action
expanding an item in a backpack into bulky is probably whacky
:cl: 
fix: You need to hold teleshield in hand to extend or contract it
/:cl:
=> You now need to hold teleshield in active hand to extend it

code/datums/materials/meat.dm, code/game/objects/items/food/_food.dm
Ports https://github.com/tgstation/tgstation/pull/60696
Meat having the reagents it should is important, I like turning people into Gondolas.
:cl:
fix: Meat has the proper reagents now.
/:cl:
=> Ports Meat Reagent Fix from /tg/

_maps/deltastation.json, _maps/icebox.json, _maps/kilostation.json, _maps/metastation.json
As it says on the tin.
Who in their right minds merged this buff in the first place???
:cl:
del: Removed cook CQC from bar areas.
/:cl:
=> [IDED] [MAJOR SKILL ISSUE] Remove bar CQC

code/game/machinery/doors/airlock.dm, code/game/objects/items/dualsaber.dm, code/game/objects/items/melee/energy.dm
Allows slicing open airlocks with esword.
https://www.youtube.com/watch?v=K48M2S7bkSA
:cl:
add: Added slicing airlocks open with energy swords.
/:cl:
=> esword airlock slicing

_maps/map_files/DM/mech_madness.dmm, _maps/map_files/DM/ragecage.dmm, code/modules/deathmatch/deathmatch_loadouts.dm, code/modules/deathmatch/deathmatch_lobby.dm, tgui/packages/tgui/interfaces/DeathmatchLobby.js
Fixes mech madness having no cells in inducers 
Fixes a mistake with syndicate loadout
Fixes lobbies not handling lack of spawns right
=> Deathmatch fixes again, I am getting tired of making these.

code/__DEFINES/maths.dm
=> Fix a floating point error

.github/workflows/ci_suite.yml, code/__DEFINES/rust_g.dm, dependencies.sh, tools/ci/ci_dependencies.sh, tools/ci/install_ripgrep.sh
=> Update rustg to 3.3.0

code/modules/reagents/chemistry/recipes.dm, code/modules/reagents/chemistry/recipes/others.dm
More like "re-adds" because *someone* just deleted the reaction code.
You'll see next time I roll antag.
:cl:Thebleh
fix: Eigenstasium can once again be made.
/:cl:
=> Fixes Eigenstasium creation
