AetherStation/AetherStation13

code/modules/vehicles/mecha/mech_fabricator.dm
Press ALT on an unscrewed exofab to change it's output dir.
Quality of life.
:cl:
qol: Alt-click an exosuit fabricater while it's maintenance panel is open to change it's output direction!
/:cl:
=> Allows you to change exofab output dir

_maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/IceBoxStation/IceBoxStation.dmm, _maps/map_files/KiloStation/KiloStation.dmm, _maps/map_files/MetaStation/MetaStation.dmm, code/modules/clothing/gloves/color.dm
the insulated gloves have the chubby finger trait no more, in addition they now spawn in the tool storage as they should.
also fixes the missing spot in the icebox's maint pipeline.
you dont need to take the insuls off to use a tablet or something and the insuls fights are back.
:cl:
qol: insuls no longer have the chubby finger trait
balance: the insuls in the tool storages are back
/:cl:
=> Returns the insulated gloves to their previous glory

code/datums/shuttles.dm, code/game/machinery/computer/communications.dm
Oh, Hi Daniel
Disco inferno
You now get them via emagging the console ONLY. It's not impossible to buy them anymore, but it requires a traitor to emag the console AND buy the thing, which shows their name in full to everyone.
I doubt this will lead to scenarios where oh hi daniel gets bought the majority of rounds.
:cl:
expansion: If you can emag the communications console, you'll find two old shuttles return...
/:cl:
=> Re-adds 2 shuttles

code/datums/elements/climbable.dm
LAZYADDASSOC has been replaced with LAZYADDASSOCLIST, as was the case before the [cybernetics PR.](https://github.com/AetherStation/AetherStation13/pull/1)
What it says on the tin. Being able to climb tables is good. 
:cl:
fix: You can climb tables more than once again.
/:cl:
=> Fix runtimes when cancelling table climbing. 

code/game/machinery/doors/airlock.dm, code/game/objects/items/emags.dm, code/game/objects/items/storage/uplink_kits.dm, code/modules/uplink/uplink_items.dm
Merges the Doorjack and the Emag into a single 6 tc traitor item.
The new emag can freely hack everything it could, but similarly to the doorjack it now costs charges to specifically hack airlocks.
It has 3 charges and recharges 1 every minute.
Requested.
:cl:
balance: The Doorjack and the Emag have been merged into the old Emag.
balance: Emag cost 4 TC -> 6 TC, can now hack airlocks at the price of rechargeable charges (3 max).
del: The Doorjack no longer exists.
/:cl:
=> Brings back the old emag, slightly nerfed

code/game/objects/structures/displaycase.dm
Older ID requirements were ridiculous. This fixes that.
This PR will let captains open their display case in a more polite way.
:cl:
qol: Now you don't have to break the display case every single time as the captain.
/:cl:
=> Fix captain's display case access

code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Dynamic could runtime for some antags if there were no candidates, PR title:
`Checks there are candidates for dynamic rulesets roundstart`
No longer runtimes.
:cl:
fix: A lack of candidates for certain antags will no longer runtime
/:cl:
=> Ports another dynamic fix

code/modules/holodeck/computer.dm
Players were able to disable the safety of the holodeck without the console being emagged, and without being a robot due to a series of fixes that were just ported
:cl:
fix: Fixes an exploit that allowed players to disable holodeck safety without following the proper conditions
/:cl:
=> Ports Fixes exploit that allowed players to disable the safety of holodeck consoles without the proper conditions being followed 

code/game/objects/items/grenades/chem_grenade.dm
Allows large grenades to work properly with non standard containers again (i.e. ones that aren't the 30u glass bottles or the various beakers you can obtain). This also allows you to use more ghetto reagent containers in regular chemical grenades such as cans of cola, plastic bottles or even trophy cups.
I don't think the regular chemical grenade was meant to fit non standard containers, but the large one was. It makes more sense for the regular one to be able to fit ghetto alternatives as it is the large casing that is locked behind tech and more likely to be used by chemists. Only serious balance implication I can think of is it being a bit easier to make ghetto sonic powder grenades, otherwise it's mostly QoL.
:cl:
balance: You can now load booze bottles, plastic bottles, soda cans etc …
=> Fix Large Grenades, Minor Rebalance of Regular Grenades.

code/game/objects/items/storage/toolbox.dm
Increases the capacity of the case so you can fit a speed loader or 2 with your revolver even when the case is full of clothes. This also means that you can now actually fit all the infiltrator clothes back in the case after you've taken them out, because you couldn't before, because reasons.
The infiltrator kit's purpose is to let you do nefarious, awful, sordid, devilish deeds in your very valid looking suit and swap out of it when needed with the crew none the wiser. Capacity issues hinder this. Letting you hold your old clothes in the case while you're in the suit is only fair, considering it costs 6 tc and the smuggler's satchel manages storage better for a fraction of the cost.
:cl:
fix: You can fit the entire infiltrator outfit into the case now, damnit.
balance: You can also fit …
=> Fix and Buff Infiltrator Kit.

code/game/objects/items/cigs_lighters.dm, code/modules/reagents/chemistry/reagents/drug_reagents.dm
You now receive 0.8 lung damage every 10 seconds instead of 1, because of the way that organs heal expect around half as much lung damage per cigarette as before. Nicotine addiction point gain has been nearly halved, now it takes 2 Space brand cigarettes to addict you as opposed to one.
With how lung damage works, it meant that before, every time you smoke a cigarette, your chat will get spammed with messages notifying you of lung damage being received and then healed. Smoking about 7 cigarettes completely destroying your lungs is funny but a bit overtuned. The real nightmare was addiction, it was less (but still) an issue for brands like robust and carp classic, but seriously affected were the cigarettes that forced you to smoke all reagents in the cigarette. Notably this caused Space …
=> Nerf Smoking Lung Damage and Addiction

code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm, code/modules/events/pirates.dm
This is a port from a commit authored by : Mothblocks and IndieanaJones "Add Revenant, Sentient Disease, Space Pirates, and Obsessed to Dynamic" (60281)
Brings pirates, revenants, sentient disease and obsessed into the dynamic ruleset instead of midround system.
Required for some future ports.
:cl:
code: Pirates, revenants, sentient diseases and Obssessed are now dynamic rulesets instead of round events.
/:cl:
=> Round event cleanup

code/game/machinery/doors/poddoor.dm, code/game/machinery/doors/shutters.dm
Fixes mechs being able to bump open blast doors.
Fixes #6 
:cl:
fix: Mechs can't walk into blast doors anymore to open them regardless of state.
/:cl:
=> Mechs can't bump closed blast doors open anymore

_maps/map_files/MetaStation/MetaStation.dmm
better med layout that makes more sense (no medhuds on a table in a semi public place) and has more anti tiders/vultures surgery space 
:cl:
add: go back to older version of the meta med
/:cl:
=> revert metamed to an older version

code/modules/reagents/chemistry/machinery/chem_dispenser.dm
no more grinding silver which was pointless since you can access enough of it roundstart to last for the whole game???
:cl:
add: adds back silver to the chem dispenser 
/:cl:
=> chem dispenser silver 

code/modules/mob/dead/new_player/new_player.dm
Fixes an old bug that made selecting observe during initialization not observe you automatically like it was supposed to.
:cl:
fix: Selecting observe in lobby while the game is initializing now works properly.
/:cl:
=> Fixed observe during initialization not observing.

code/game/objects/buckling.dm
You will no longer stare east when latejoining
muh immershioon
:cl:
fix: latejoin buckling sets your facing direction correctly.
/:cl:
=> Fix east stare on latejoin

code/modules/mob/dead/observer/observer.dm
Fixes an absolutely game breaking bug where if you stop orbiting as a ghost you will not have the float animation anymore.
:cl:
fix: Ghosts move up and down again after orbiting.
/:cl:
=> Fix ghost float animation breaking after orbiting.

code/modules/uplink/uplink_items.dm
It's on the tin
Its pretty stupid for noslips to be limited now as slipping is less dangerous than it used to be, 4tc cost for nukies is also stupid 
:cl:
balance: Removed poplimit from noslips, reduces their price to 2 for nukies
code: removed nukie noslip subtype
/:cl:
=> Removes poplimit from noslips and reduces cost of nukie noslips to 2 TC

code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm, tgui/packages/tgui/interfaces/ThermoMachine.js
Thermomachines no longer have a button to switch between cooling and heating modes, and instead accept any suitable value in the temperature field for both heating and cooling.
Alt-clicking a thermomachine now maximises or minimises the target temperature if it isn't at an extreme, or switches between maximum and minimum temperature if it is.
Thermomachine will now exchange gases even if it is inactive.
Changing temperatures is easier, and preset buttons are actually helpful.
Thermomachine would stop working before target temperature is reached because the internal buffer would reach a suitable temperature, and the pipe would remain at a different temperature. Now, the connected pipe will actually reach specified temperature.
:cl:
qol: Merged heating and cooling modes of thermomachine. …
=> Thermomachine improvements

code/modules/mob/mob_lists.dm
So, if you observed before the game actually starts you didn't get added to the observer list which means you aren't considered a candidate for ghost role midround rulesets. This fixes that.
=> Removes mode check from dead/observer lists.

code/__DEFINES/construction.dm, code/game/objects/items/RPD.dm, code/modules/atmospherics/machinery/datum_pipeline.dm, code/modules/atmospherics/machinery/pipes/heat_exchange/manifold.dm, code/modules/atmospherics/machinery/pipes/heat_exchange/simple.dm, code/modules/atmospherics/machinery/pipes/manifold.dm, code/modules/atmospherics/machinery/pipes/pipes.dm, code/modules/atmospherics/machinery/pipes/simple.dm, code/modules/research/designs/tool_designs.dm, code/modules/research/techweb/all_nodes.dm
When one wants to connect to an existing pipe, the only ways to do so are by either having previously planned and added a free node, or removing a pipe and adding a free node. This is a problem when in a multiplayer environment as planning is usually not possible, and removing a pipe will often result in a gas leak. This merge request adds a way to add nodes to existing pipes, without unwrenching the pipe and causing trouble. This is done by rightclicking a pipe with an RPD that has the Amend upgrade, and selecting a direction for a new node from a radial menu. Also works on heat exchange pipes. The upgrade must be researched from the Rapid Construction node, and can be printed in the engineering lathe. Previous RPD rightclick functionality (copying layer and colour of existing pipe) has …
=> Pipe Amending

code/datums/components/plumbing/reaction_chamber.dm, code/modules/reagents/chemistry/holder.dm
Pleaseworkthistimepleaseworkthistimepleaseworkthistimeplease
Re-adds the check for if reaction chamber will give reagents to ductnets, that was removed in fermichem removal.
Fixes https://github.com/AetherStation/AetherStation13/issues/131
:cl:
fix: Chems will now stop to react in reaction chamber.
/:cl:
=> Fixing Reaction Chambers Part 4 Revengeance

code/game/machinery/firealarm.dm
Lowers the fire alarm cold trigger from -3C (internal body temp damage treshold)  to -63C (it doesnt hurt you to stand around at this temp for quite a while if ever). Makes the firelocks much less likely to trigger from breaches. 
Effectively, this change makes breaches a bit more dangerous as they will vent more before the doors close. In huge rooms like main hallways, this will take 5+ minutes, and vent a lot of gas, but not below low pressure, so fine to move around in if you got internals. In small rooms, obviously will be faster but still takes a few minutes.
Does make it possible to make the fire alarms disengage by fixing the atmos "well enough" instead of having to raise temperature to tropical beach level before the fire alarms calm the fuck down.
beep beep beep beep beep beep …
=> Fire alarms now trigger on -63C instead of -3C

code/modules/modular_computers/computers/item/computer.dm, code/modules/modular_computers/hardware/CPU.dm, code/modules/modular_computers/hardware/_hardware.dm, code/modules/modular_computers/hardware/ai_slot.dm, code/modules/modular_computers/hardware/battery_module.dm, code/modules/modular_computers/hardware/card_slot.dm, code/modules/modular_computers/hardware/hard_drive.dm, code/modules/modular_computers/hardware/portable_disk.dm
Make tablet Destroy() actually delete component contents as well. This will cause both batteries and inserted ID's to be deleted if the tablet or modular computer is either deleted via the admin commands, or deleted by explosions or similar.
:cl: Skoglol
fix: Tablet batteries and ID's now properly delete.
/:cl:
=> Tablet batteries and ID's now properly delete

code/modules/projectiles/projectile/bullets/shotgun.dm
Adjusts buckshot damage from 7.5 to 10 per pellet, up to a total of 60 damage.
Adjusts slug damage from 50 to 35 and it's armor piercing to 30.
It makes buckshot actually good again while also making slugs less powerful while giving them a seperate use case.
:cl:
balance: Buckshot now does 60 damage if all pellets land.
balance: Shotgun slugs now do 35 damage, but have an armor piercing value of 30.
/:cl:
=> Adjusts buckshot and slug damage.

code/controllers/subsystem/id_access.dm, code/game/objects/items/cards_ids.dm
I am really bad at writing these.
:cl:
fix: Space ruin ID cards have the correct access again.
/:cl:
=> Fix some away IDs and make AA-chip programmer work with templates properly

code/modules/clothing/outfits/ert.dm, code/modules/jobs/job_types/head_of_security.dm, code/modules/projectiles/guns/ballistic/automatic.dm, code/modules/projectiles/guns/ballistic/rifle.dm, code/modules/projectiles/guns/ballistic/shotgun.dm, code/modules/projectiles/guns/energy/energy_gun.dm, code/modules/projectiles/guns/energy/laser.dm, code/modules/projectiles/guns/energy/pulse.dm, code/modules/projectiles/guns/energy/special.dm, code/modules/projectiles/guns/special/blastcannon.dm
Energy guns, bulldogs, wormhole guns, reverse engineered ebows and more can fit in backpacks again. Reverts several changes to item size from https://github.com/tgstation/tgstation/pull/54041 and https://github.com/tgstation/tgstation/pull/56132
Reverts unnecessary flavour texts from the latter too, they're a pet peeve that annoys me, the game already tells you the items are normal sized, why do you need to specify in the description too.
People carrying tons of guns is not an issue, carrying tons of guns in your backpack means you have nothing but guns and you just die. What bulky guns does do is prevent people from concealing weapons. This game is not about telegraphing every single attack you have to make things fair for other players, people will use dirty tactics including concealed …
=> Reverting /tg/'s bulky guns, or at least the ones I know of.

_maps/map_files/MetaStation/MetaStation.dmm
removes those awkard airlocks from maintbay
too many airlocks
:cl:
fix: removed abundant airlocks from maintbay
/:cl:
=> remove abundant airlocks from maintbay

code/game/machinery/recycler.dm
Makes the recycler enter safety mode immediately before being dismantled to prevent it eating its own parts
Credits to GoblinBackwards
broke thing be fixed unga
:cl:
fix: Recyclers no longer eat their own parts when dismantled.
/:cl:
=> Prevents the recycler from eating its own parts when dismantled

code/modules/vehicles/mecha/combat/durand.dm
Makes sure the Durand's shield is resistant against fire, lava and acid; three things that could infinitely damage the shield even if it was turned off. 
Fixes a bug where the durand shield constantly takes damage ad infinitum, while also draining it's battery.
It's more of a bug fix than a balance change since mechs are normally immune to both fire and acid damage.
:cl:
fix: The Durand's shield does not take damage from fire and acid anymore, as it would burn infinitely long.
/:cl:
=> Stops Durand shield from taking infinite damage.

code/datums/mind.dm, code/game/objects/items/implants/implantuplink.dm
If you roll midround and have lost all the other uplink options, getting an uplink implant charges you 4 TC currently.
For some reason if you had the pen preference, it would not fall back on PDA or radio either, added those.
Removed the implant fallback cost if you do not have the implant preference, it shouldn't happen very often with the pen preference fallbacks added.
Removed the "for a small TC fee" texts, the mind one would never trigger and the other is harder to adjust. The cost is obvious when you pick the preference.
Midrounds happen all the time, they are likely already much lower power level comparatively so we shouldnt nerf them further.
:cl: Skog
balance: Traitor uplink implant fallback no longer costs 4 TC. If you have the uplink preference, nothing has changed and you will …
=> Removes uplink implant cost when its not your preference

code/game/objects/items/control_wand.dm
On the tin.
Fixes #180 
:cl:
fix: Door remotes no longer have all access.
/:cl:
=> Fixes remotes having all access.

code/game/objects/items/circuitboards/machine_circuitboards.dm, code/modules/mining/machine_redemption.dm
ORM now takes part upgrades into account again. 
Matter bin and Micro laser upgrades sheet generation. Starts at 0.75 sheets per ore (down from 1) at tier 1, tier 2 is old normal. Maxes out at 1.5 sheets per ore.
Micro-manipulator increases point gain. To avoid punishing miners for quickly bringing minerals home, will be 100% on tier 1 and 2 parts. Tier 3 and 4 will be upgrades, maxing out at 150%.
To avoid quite as easily moving it to lavaland, the ORM is now unable to be unwrenched. If you need to move it, you will have to deconstruct it, which includes re-linking it to the ore silo.
Believe it or not, non miners use the ORM.
:cl: Skog
balance: ORM can no longer be wrenched and moved.
balance: The ORM can now have its parts upgraded again! Tier 2 parts give the same amount of materials …
=> Readds upgrades to ORM, anchors it

code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
War ops >>>>> stealth ops. Small crews should benefit more from the early warning as well, as disk holders often are very easy to pick off alone without one.
Changed the names of the defines as they made for a very wide equation.
Less surprise delta.
:cl: Skog
balance: Nuke op war limit reduced to 25 players, with a scaling reward. 60 TC extra minimum, 220 TC more depending on how close to the old minimum of 50 players the server is.
/:cl:
=> Lowers nukeops war limit to 25 players, scaling TC reward

code/game/objects/items/storage/bags.dm
Makes it so plant bag, chemistry bag, etc etc fits in your bag. The belt only change largely just contributes to being an annoyance, leading to a lot of inventory switching back and forth. This is clunky.
Nerfs by clunk are bad.
:cl: Skog
balance: Job bags (plant bag, chemistry bag, contruction bag etc etc) are now normal sized down from bulky, and fits in your backpack.
/:cl:
=> Reverts bulky job satchels, makes them normal sized

code/modules/antagonists/revolution/revolution.dm
Ports: https://github.com/tgstation/tgstation/pull/63936 by Ryll-Ryll
> Currently rev deconversions are logged directly to game.log, rather than being registered in the player's attack logs like cult deconversions. This makes it like cult deconversions so admins can see them
> Logging consistency
:cl: Ryll/Shaps
admin: Log messages for being deconverted from a revolution are now also registered in the mob's individual logs instead of just to the game.log
/:cl:
=> Fixes revolution logging Port from tgstation

code/game/objects/items/RSF.dm, code/game/objects/items/robot/robot_items.dm
Lowers cooldown on cookie and candy generation for borgs. Also increases the amount of candy for the mediborg, and reducing the damage of the gumballs when emagged.
These were never a problem that needed fixing.
:cl: Skog
balance: Peacekeeper borgs can now dispense cookies faster, and mediborgs get more candy storaage and lower cooldown. Lowered the emagged gumball damage to compensate.
/:cl:
=> Lowers cooldown on borg cookies and candy

code/game/objects/items/storage/firstaid.dm, code/modules/reagents/reagent_containers/hypospray.dm
The kit now comes with 4 of the T3 medipens, 2 for brute, 2 for burn.
The hypospray has been adjusted, it now has a 100u capacity and it no longer has epi. Instead, I've reduced the amounts of atropine and leporazine by 5u each, added 20u sanguirite and replaced epi with salbutamol. This means that the injector can now help treat bleed wounds and fractures.
~I'm dead~ Nukies suffer in terms of healing, ~I died,~ they only get a few patches on the shuttle and because they've been cobbychemd they only contain 2u of decent meds each. Also getting a bleed wound was a massive trouble for nukies and giving them a coagulant makes it much more tolerable. 
:cl:
balance: Combat medic kit has good meds now, and its hypospray also contains coagulant and morphine.
/:cl:
=> Buffing Nuke Op Combat Medic Kit.

code/game/objects/structures/crates_lockers/closets/secure/security.dm, code/modules/cargo/packs.dm, code/modules/projectiles/boxes_magazines/internal/shotgun.dm, code/modules/projectiles/guns/ballistic/shotgun.dm, code/modules/projectiles/projectile/beams.dm, code/modules/research/designs/autolathe_designs.dm, code/modules/research/designs/weapon_designs.dm, code/modules/research/techweb/all_nodes.dm
you can now print slugs and buckshot like in the good old days and also slightly buffs riot shotgun's firing speed and makes the pulse slug deal 40 damage (also re adds the lethals locker if you want to map it)
the slugs and buckshot have been tweaked a bit to be less powerfull also pulse slugs were nerfed despite not even being good 
:cl: Pepsiman
add: good shotgun ammo is printable again
add: pulse slugs deal 40 damage 
/:cl:
=> re adds printable slugs and buck plus minor balance change

code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
Alt click rotate didn't work on circulators because it tried to make you vent crawl.
fixes #240.
:cl:
fix: fixed not being able to rotate TEG circulators with alt-click.
/:cl:
=> Fix not being able to alt click rotate TEG circulators.

code/modules/antagonists/wizard/equipment/soulstone.dm
Fixes an issue where when making a cult construct it would create two constructs.
fix bug, bug go away, me happy.
:cl:
fix: fixed cult made cult constructs being doubled.
/:cl:
=> Fixes cult constructs doubling.

code/modules/power/cell.dm
Removes charge overlays from slime cells.
fixes #246.
:cl:
fix: slime cells no longer have a charge overlay.
/:cl:
=> Fixes slime cells having overlays

code/modules/antagonists/traitor/datum_traitor.dm
This PR will fix changelings getting their absorb stuck after absorbing a traitor due to the objectives spitting null values into memories.
Bugfixing = Good
:cl:
fix: Traitor objectives no longer spit null values
/:cl:
=> Fix traitor objectives spitting NULLs

code/game/objects/structures/reflector.dm, tgui/packages/tgui/interfaces/Reflector.js
The lack of responsivness in refrectors hurt me greatly whenever I wanted to make them aim properly, this makes it significantly faster and adds some presets
~~Currently the UI looks like this: ~~
~~If anyone has an idea how to make the buttons space better there please let me know.~~
Thanks to @TheChosenEvilOne for helping me with making ui better, now it looks like this:
https://user-images.githubusercontent.com/53384660/185946751-589f5f8e-e567-4c9e-8d19-d664087dfeb1.mp4
It also got enchanced with buttons on suggestion from skog, that allow you to change the angle in smaller amounts.
the reflectors are more responsive and can be used for more interesting purposes easier
[lasering.webm](https://user-images.githubusercontent.com/53384660/185815570-e64c195f-ae38-4bd1-9106-6ecedf78bb8f.webm) …
=> Add secondary, tgui menu for reflectors

code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Removes the modifier from ANFO, and doubles the divisor. It will be more like a weaker meth now.
Imagine thoughtfully calculating and designing several multi part explosive chems that require complex recipes and reward you for your hard work with powerful explosives... then some guy adds a reagent with 1:1 ingredient to output ratio that outperforms all but TaTP and nitro (the ones which require lavaland chems) in every single way - easier to make, bigger boom, hell you don't even really need to interact with chemistry, just a biogen and a fuel tank.
:cl:
balance: anfo has been nerfed severely.
/:cl:
=> Nerfs ANFO Severely

code/modules/antagonists/heretic/eldritch_book.dm
Codex Cicatrix only checks if you have enough charges in the UI, so you could very trivially modify the UI to disable the cost check. This PR just adds a cost check in the `ui_act` of the Codex Cicatrix.
=> Fixes href exploit in codex cicatrix.

code/modules/research/rdconsole.dm
When saving designs to a design disk from a research console the console doesn't actually check if you have that design researched. This PR adds the missing check to `ui_act` of the research console.
=> Fixes href exploit in research console.

code/game/objects/items/stacks/stack.dm
With item stack crafting you could modify the UI to set the crafting multiplier to a very tiny number to craft things for practically free. This is easily fixed by just rounding the multiplier.
=> Fixes href exploit in item stack crafting.

code/game/objects/items/RPD.dm
RPD doesn't check if the piping layer set in the UI was actually with in the allowed range.
it also allows decimal layers a seen here:
This PR fixes those issues by rounding the value and clamping it in `ui_act`.
=> Fixes href exploit in RPD regarding pipe layers.

code/__DEFINES/keybinding.dm, code/datums/keybinding/human.dm
Adds quick equip keybinds for pocket slots.
It makes no sense that you can quick equip from bag, belt, and armour slot but not from pockets, so here we are. Also less clicking more gaming.
:cl:
add: Added quick equip keybinds for pocket slots Shift+R and Shift+F for right and left pockets respectively.
/:cl:
=> Pocket quick equip keybinds.

code/modules/vehicles/mecha/_mecha.dm
Fixes the Phazon and Savannah-Ivanov going very fast upon meeting a dull, universal force.
Literally a bugfix, come on now.
Fixes #262 
:cl:
fix: Mechs do not go super fast anymore upon meeting a dull, universal force.
/:cl:
=> Fixes mechs going sanic speeds.

code/modules/deathmatch/deathmatch_controller.dm, code/modules/deathmatch/deathmatch_lobby.dm, tgui/packages/tgui/interfaces/DeathmatchLobby.js
Even more improvements to deathmatch.
When creating a lobby a deadchat message is displayed with a link to join, and added a toggleable deathmatch chat.
:cl:
add: Added a dead chat message when a new deathmatch lobby is created.
add: Added chat to deathmatch that can be toggled in lobby.
/:cl:
=> Deathmatch improvements.

code/datums/components/overlay_lighting.dm, code/game/atoms_movable.dm
Ports tgstation/tgstation#60756.
Yes, this is an ided bug fix PR.
:cl: Couls
fix: bright white spheres when attacking things with an item that has a light source attached
fix: inventory and action buttons creating light sources
/:cl:
=> Fix light overlay issues, ports TG PR 60756.

code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm, code/modules/antagonists/traitor/datum_traitor.dm
Fixes #281, also fixes traitors not getting codewords in notes.
:cl:
fix: Fixed roundstart cultist not being informed about their objectives.
fix: Fixed traitors not having codewords in notes.
/:cl:
=> Fixes two issues with antag notes (memory).

code/modules/deathmatch/deathmatch_loadouts.dm, code/modules/deathmatch/deathmatch_lobby.dm, code/modules/deathmatch/deathmatch_maps.dm
Removed headsets from operator loadout, also fixed dying players not getting added to global chat. ALSO ALSO hopefully fixed the weird issue with people being able to play maps with wrong loadouts.
I hate making so many small PRs to fix issues I should have noticed ages ago.
:cl:
fix: removed headset from deathmatch operator loadout.
/:cl:
=> More deathmatch fixes.

code/__DEFINES/access.dm, code/game/objects/items/circuitboards/circuitboard.dm, code/game/objects/items/circuitboards/computer_circuitboards.dm, code/modules/research/nanites/nanite_cloud_controller.dm, tgui/packages/tgui/interfaces/NaniteCloudControl.js
This PR is going to add a brand new feature from the NT for nanite cloud controllers called the SciLock. This feature will require crewmembers' IDs to have RnD access to log into a nanite cloud controller (Borgs and AIs don't have to worry though since they don't have to authenticate). This feature may be disabled with a use of multitool on a borad or hacked with a use of cryptographic sequnecer on a board or the machine itself.
This PR also will improve some circutboard.dm code.
It prevents non-antags from griefing while not gatekeeping nanites to a single department. In addition, there will be another use for the cryptographic sequencer.
Also, some code improvements.
:cl: Polish_User, TCEO, SparkezelPL, TheBleh
add: Added SciLock for Nanite Cloud Controllers
code: Improved …
=> Added a SciLock feature to Nanite Cloud Controllers and refinined circuitboard code

code/modules/clothing/suits/wintercoats.dm
Reducing bomb, laser and energy by 10, increasing bullet by 5 to compensate as unlike other HoS clothes this doesn't cover legs.
Stupid powercreep stats made to tank an extra disabler hit, used by unrobust people, now you can wear it without being a walking talking metaphor for shame. Yes 1 extra disabler hit is a lot when it's 7 instead of 6. Anyone who defends this should not be taken seriously!!!!
:cl:
balance: HoS wintercoat has been rebalanced, it now takes as many disabler hits to down as any other HoS armour.
/:cl:
=> Nerfing HoS Winter Coat

_maps/map_files/MetaStation/MetaStation.dmm
fixes #280, replaces borg charger in medbay with NanoDrug Plus because silicons have no rights.
:cl:
add: Added a NanoDrug Plus vendor to medbay in MetaStation.
/:cl:
=> Added NanoDrug Plus to Meta medbay.

code/modules/atmospherics/environmental/LINDA_turf_tile.dm
As it turns out engine floor has a heat capacity of INFINITY, and because superconductivity shares gas temperature with floor temperature it just straight up removes heat, very cool.
:cl:
fix: Fixed engine floors destroying gas heat.
/:cl:
=> Fixes heat disappearing on reinforced floor.

code/controllers/subsystem/materials.dm, code/game/objects/items/stacks/sheets/glass.dm, code/game/objects/items/stacks/sheets/mineral.dm, code/game/objects/items/stacks/sheets/sheet_types.dm
Gives timers to a lot of stack recipes that didn't have timers, such as floodlights, carving blocks and windows.
People spamming instant place non passable projectile proof structures x5 to cut off chases is too egregious.
:cl:
balance: most material recipes which make unpassable objects that didn't have timers now do.
/:cl:
=> Adds Timers to a Lot of Material Recipes

code/datums/components/customizable_reagent_holder.dm, code/datums/components/food/edible.dm
Makes custom food reagent holders get larger when ingredients are added so all reagents can fit, also makes deepfrying food inherit the reagent holder size. (why wasn't this done like this already?)
Eating this will actually make you really fat.
:cl:
add: Made custom foods able to hold all reagents of added ingredients.
add: Made deepfried items inherit reagent holder volume.
/:cl:
=> Makes custom foods able to hold all reagents of ingredients.

code/datums/status_effects/debuffs.dm
Makes stasis stop chem reactions in mobs.
You will be able to do some funny stuff.
:cl:
add: Stasis now stops chem reactions in mobs.
/:cl:
=> Makes stasis prevent chem reactions in blood.

code/datums/components/slippery.dm
Ports https://github.com/tgstation/tgstation/pull/60626
Fixes https://github.com/AetherStation/AetherStation13/issues/294
It's not, I like permanent invisible slips.
:cl:
fix: bananium mk2 clown shoe peels no longer make tiles permanently slippery.
/:cl:
=> Ports Phantom Slip Fix From /tg/

code/game/objects/items/food/snacks.dm
Another 2 year old floyd bug.
Fuck floyd.
:cl: Thebleh
fix: South Bronx Paradise Bars are once again the best weight loss aid on station
/:cl:
=> Fixes the south bronx paradise bar

code/modules/reagents/chemistry/recipes/slime_extracts.dm, code/modules/research/xenobiology/xenobiology.dm
Adds back felinid mutation toxin to green slime extracts, to make it you need to inject it with water :)
If you want to counter it you need to quickly sip some multiver or pentetic, both should work
Readds it to its rightful place
:cl:
add: You can make felinid mutation toxin by injecting green slime extract with... water, chug multiver quick to avoid it
/:cl:
=> Readds felinid mutation toxin to green extracts

code/modules/reagents/reagent_containers/spray.dm
Increases puff_reagent_left tenfold for streams,  removes check for standing up for applying chems to mobs, fixes chem sprayer having stream set to 5u and not 10u.
This stops stream from not working as soon as there is blood or any items on the same turf as the person you are spraying. If it's still cluttered it will block it, covering yourself in a pile of random shit to block chems can be a feature. Nuke op sprayer is incredibly weak, partly because it was bugged, now it isn't and it can go from decent to absurdly strong (if you spray someone against a wall several sprays will hit them at once and they'll get several units of each poison as opposed to usual 3u of each give or take)
:cl:
fix: Spray stream is more likely to effect mobs when tiles have several turfs, biochem sprayer now …
=> Fixing And Buffing Sprays

code/modules/reagents/chemistry/machinery/chem_dispenser.dm
This will force all chem dispensers to ALWAYS show buttons in range of ( 5, 10, 15, 20, 25, 30, 50, 100, 300 ) which is same as a BS beaker range
Its fucking stupid when you put a spray into a chemdispenser and you can only rtransfer the amounts in values of 5 or 10 units, or 2/5 for space cleaners
this makes it sane
:cl:
qol: Chemdispenser now have fully unlocked reagent synthesis ranges
/:cl:
=> makes chem dispensers saner

code/modules/mob/living/carbon/human/species.dm
Allows you to quickly steal shoes again
Great for tactical glass shards (and just stealing shoes in general)
:cl:
add: Readds shoestealing
/:cl:
=> FEET (readds shoe stealing)

code/__DEFINES/flags.dm, code/game/atoms.dm, code/game/objects/items/storage/secure.dm, code/game/turfs/closed/wall/reinf_walls.dm, code/game/turfs/closed/walls.dm, code/game/turfs/open/chasm.dm, code/game/turfs/open/floor/fancy_floor.dm, code/game/turfs/open/floor/iron_floor.dm, code/game/turfs/open/floor/plating.dm, code/game/turfs/open/lava.dm, code/game/turfs/open/openspace.dm, code/game/turfs/open/space/space.dm, code/game/turfs/open/water.dm, code/game/turfs/turf.dm, code/modules/antagonists/heretic/knowledge/rust_lore.dm
Fixes https://github.com/AetherStation/AetherStation13/issues/182
You can rust or destroy specific objects and turfs with your mansus grasp with the rust path properly again.
:cl:
fix: fixes rust heretic not being able to properly rust or destroy specific objects/turfs
/:cl:
=> Fixes not being able to rust with your mansus grasp

code/modules/antagonists/cult/blood_magic.dm
Makes cult stuns ignore stun immunity.
~~Fuck you Delt.~~ Cult is quite powerless early game with the stun being their only tool they can use, when someone gets hulk three minutes in the round and can completely ignore cult stuns it pretty much guarantees cult getting outed. Also cult stun already has it's counter in the form of holy melons and anti-magic in general.
:cl:
balance: cult stun now ignores stun immunity.
/:cl:
=> [IDED] [MAJOR SKILL ISSUE] Makes cult stun ignore stun immunity.

code/modules/antagonists/cult/blood_magic.dm, code/modules/antagonists/cult/cult_items.dm, code/modules/antagonists/cult/cult_structures.dm
This PR will rebalance the blood cult's equipment:
-Bring back the mirror shields to the forge
-Remove the block chance from daggers/longswords
-Bring back longswords to summon equipment
Block chance on daggers/swords is annoying to deal with and in the current state of our codebase bringing back cult shield is fair.
:cl:
balance: replaced longswords with mirror shields in cult forge
balance: added back longswords to summon equipment
balance: removed block chance from longswords/daggers
/:cl:
=> Bring back the cult shield and rebalance the daggers/longswords

code/modules/clothing/head/misc_special.dm
This PR will buff Ecak to have simillar damage stats and qualities as an esword.
Ecak is basically an esword put into a cake, therefore, it should have some esword stats preserved. 
:cl:
balance: energy cakehat does esword dmg, can delimb and has esword armour penetration
/:cl:
=> Making things right.

code/game/objects/items/robot/robot_upgrades.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/silicon/robot/robot_defines.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
This PR re-adds the standard cyborg model!
- Moved the zipties to the emagged section. I'm sure everyone can appriciate this change.
A standard playstyle is good for borgs who are either new to the game or simply don't know what to do (yet).
Borgs are a different playstyle in their own right, there's no real need to hyper specialize them into certain jobs, especially for LRP servers such as ours.
:cl:
add: The default cyborg has returned!
balance: The default cyborg's zipties have been moved to the emag-only section.
/:cl:
=> Re-adds the standard cyborg!
